### ISSUE TITLE
Thermal expansion simulation

### ISSUE THREAD

**Issue by ruibmpinto** [TarletonGroup/CrystalPlasticity#81] opened 2024-11-01 01:06 UTC
Dear Developers,

Is it possible to run a coupled thermal-displacement expansion simulation with a varying thermal profile (passed as an amplitude within abaqus) as a boundary condition? 

I understand I must change the element type to CPE4T (e.g., for 2D) in the meshprops.f file to include temperature and change the step type to "coupled temp-disp", but I believe only a predefined temperature field can be assigned and not as a boundary condition varying in time, right?

Best wishes,
Thanks for the great UMAT

**Comment by EralpDemir** [comment] 2024-11-01 10:45
Hi,

That is a good question. 

Exactly, the element type is currently determined automatically based on the dimension of the problem (2D or 3D) and number of integration points. 

The temperature is transferred to UMAT with TEMP variable. But it is by default set to a constant temperature in the code currently. You must change the flag "constanttemperature=0" in line 193 at "userinputs.f" file. Then UMAT will use the temperature you enter either from a thermal field solver or predefined value. 

You may use a thermal solver as well, it does not have to be a predefined temperature.

Let us know how it works, never used a thermal solver with UMAT, it may introduce complications during initialization. 

Best,
Eralp

**Comment by ruibmpinto** [comment] 2024-11-25 15:08
Hi,

Yes, exactly, I have also changed that flag but forgot to mention it.

Everything seems to work fine - I am still benchmarking the solution. 

However, there is something that is not clear. In the PROPS.xlsx file, sheet 'Description', line 100, is it the von Mises stress or the strain that is output? If I go to useroutputs.f lines 50-53, it states "Equivalent Von-Mises plastic total strain", but then in the Excel it mentions the stress...

I am guessing the stress is written directly to the abaqus quantity S, so it must be the plastic strain, right?

If not, is there a way to output the plastic strain, since it is not written to PE?

Thank you,
Best wishes,
Rui

**Closed** 2024-11-25 16:00 UTC

**Comment by JNPDream** [comment] 2024-11-29 11:34
Dear Developer,

During the calculation process, we found that altering the parameters does not change the stress-strain curve. We are quite confused about this issue. We are using hardening model 5. Could you please help us understand why this might be happening?
> Best， Eralp

**Comment by EralpDemir** [comment] 2024-11-29 17:12
The code is written for many state variables but indeed many of these are not used. 

I guess hardening model-5 is similar to Kocks Mecking hardening. You need to initialize a dislocation density value, it must be non zero.  This is referred as "rhoSSD" in usermaterials.f file. Try setting it to 1 micrometer^-2.  

Best

**Comment by JNPDream** [comment] 2024-11-30 15:43
Thank you so much for your detailed and insightful reply; it has been
incredibly helpful for my work. Additionally, I have three questions I’d
like to consult with you: :

   1.

   Firstly, in the *hardening.f* file and the *crss file (subroutine
   totalandforest)*, both involve the calculation of dislocation density. I
   would like to seek your advice on the relationship and differences between
   these two implementations.
   2.

   Secondly, regarding the unit system in your provided subroutine, the
   length unit is in micrometers. Can I then understand that if the calculated
   stress is 100, it should be interpreted as 100 N/μm², which equals 100×10
   6MPa?
   3.

   Lastly, I would like to know how to rewrite this subroutine into a
   *VUMAT* format.

Once again, thank you for your support and generosity in sharing your
knowledge. Your expertise has been an invaluable resource for me, and I
sincerely hope to continue learning from you in the future.

Best regards,

Guojin Xiang


Eralp Demir ***@***.***> 于2024年11月30日周六 01:13写道：

**Comment by JNPDream** [comment] 2024-12-03 14:40
Eralp, hello!

I sincerely thank you for your response. Your work has provided tremendous
help to us, and I will carefully follow the approach you suggested. I truly
hope we will have the opportunity to communicate and collaborate again in
the future. Thank you once again from the bottom of my heart!

Best regards,

Guojin Xiang

Eralp Demir ***@***.***> 于2024年12月2日周一 21:41写道：

**Comment by JNPDream** [comment] 2025-01-08 07:55
Dear  Eralp  ,

I hope this email finds you well. I apologize for bothering you again, but
I’m currently facing a challenging issue and would greatly appreciate your
guidance.

In my calculations, my model needs to account for dynamic
recrystallization. As such, the stress-strain curve is expected to decrease
after reaching the saturation stress and gradually stabilize. However, no
matter how I adjust the values of k1 and k2, I’m unable to achieve a
decreasing trend in the curve. Moreover, when I set k2 to an extremely
large value, an error occurs.

Attached are my inp file and subroutine file for your reference. I
sincerely apologize for the inconvenience caused by this repeated request
for help.

Thank you in advance for your time and assistance!

Best regards,

Guojin Xiang

K Kk ***@***.***> 于2024年12月3日周二 22:40写道：
