### ISSUE TITLE
The executable standard.exe aborted with system error code 1073741819

### ISSUE THREAD

**Issue by xiamucp** [TarletonGroup/CrystalPlasticity#16] opened 2023-07-11 01:56 UTC
I simulated uniaxial tensile according to the video introduction, but an error occurred.
The executable standard.exe aborted with system error code 1073741819. Please check the .dat, .msg, and .sta files for error messages if the files exist.  If there are no error messages and you cannot resolve the problem, please run the command "abaqus job=support information=support" to report and save your system information.  Use the same command to run Abaqus that you used when the problem occurred.  Please contact your local Abaqus support office and send them the input file, the file support.log which you just created, the executable name, and the error code.
Could you help me? Thanks

**Comment by EralpDemir** [comment] 2023-07-11 08:36
Hi,
In the earlier version the code, there was a fortran file which was reading the abaqus *.INP file. But we realized that it does not work well in some systems. So the number of elements (the variable "numel") and the element type ("eltyp") shall be entered manually at userinputs.f file.

Could you check this and let me know if the problem is something else.

Bests,
Eralp

**Comment by xiamucp** [comment] 2023-07-11 09:06
Thanks for your attention,
UMAT 1.36 is used in my works,  the variable "numel" and element type "eltyp" is defiend accurately.  In fact, the error often occurs after slip systems are hardened.

 At the end of increment:           26
 States are updated!
 --------------------------------
 --------------------------------
 At the end of increment:           27
 States are updated!
 --------------------------------
2023/7/11 15:33:56
Abaqus Error: The executable standard.exe
aborted with system error code 1073741819.
Please check the .dat, .msg, and .sta files for error messages if the files
exist.  If there are no error messages and you cannot resolve the problem,
please run the command "abaqus job=support information=support" to report and
save your system information.  Use the same command to run Abaqus that you
used when the problem occurred.  Please contact your local Abaqus support
office and send them the input file, the file support.log which you just
created, the executable name, and the error code.
Abaqus/Analysis exited with errors

Bests,
Xia

**Comment by xiamucp** [comment] 2023-07-11 09:06
> Hi, In the earlier version the code, there was a fortran file which was reading the abaqus *.INP file. But we realized that it does not work well in some systems. So the number of elements (the variable "numel") and the element type ("eltyp") shall be entered manually at userinputs.f file.
> 
> Could you check this and let me know if the problem is something else.
> 
> Bests, Eralp
Thanks for your attention,
UMAT 1.36 is used in my works, the variable "numel" and element type "eltyp" is defiend accurately. In fact, the error often occurs after slip systems are hardened.

At the end of increment: 26
States are updated!
At the end of increment: 27
States are updated!
2023/7/11 15:33:56
Abaqus Error: The executable standard.exe
aborted with system error code 1073741819.
Please check the .dat, .msg, and .sta files for error messages if the files
exist. If there are no error messages and you cannot resolve the problem,
please run the command "abaqus job=support information=support" to report and
save your system information. Use the same command to run Abaqus that you
used when the problem occurred. Please contact your local Abaqus support
office and send them the input file, the file support.log which you just
created, the executable name, and the error code.
Abaqus/Analysis exited with errors

Bests,
Xia

**Comment by EralpDemir** [comment] 2023-07-11 09:40
Hi Xia,

Thanks for the update. 

I have put the v1.35. Could you please run this as well and let me know if you have the same issue?

If the same problem happens again, then it is not due to the updates. You cut off GND or SSD hardening initially and gradually add those effects.

Thanks,
Eralp

**Comment by xiamucp** [comment] 2023-07-11 12:14
> Hi Xia,
> 
> Thanks for the update.
> 
> I have put the v1.35. Could you please run this as well and let me know if you have the same issue?
> 
> If the same problem happens again, then it is not due to the updates. You cut off GND or SSD hardening initially and gradually add those effects.
> 
> Thanks, Eralp
Hi,
UMAT v1.35. worked! Thank you very much for your help!

Thanks,
Xia

**Comment by EralpDemir** [comment] 2023-07-13 09:08
Dear Xia,

I have checked and corrected the v1.36. 

Please use this version since it involves the correct the integration of Fp.

With that I close this issue. Please feel free to raise another issue if you encounter any problem running the code.

Best wishes,
Eralp

**Closed by EralpDemir** 2023-07-13 09:08 UTC

**Comment by xiamucp** [comment] 2023-08-04 03:23
Dear Eralp,

I’m sorry to disturb you.

I have tried the UMAT v2.1. And I found that the forest dislocation density always equal to 0, even though both ssd and gnd are viriable. (hardening model == 3, explicit)

I'm looking forward to your reply, thanks! 

Bese wishes,
Xia

**Comment by EralpDemir** [comment] 2023-08-04 05:40
Hi Xia,
Please feel free to ask questions anytime.

The hardening model 3 requires an initial density. These densities are set by the user for each material in usermaterial.f. The variable is "rho0" I believe. That is the reason you are getting forest density as zero. These densities are projected to the slip systems to get forest density. 

If you turn GND density on, you would also get forest densities.

Please do not confuse the projected forest density with the forest state variable (statev_forest) which is a separate state variable used in hardening model=4 for alpha-uranium.

Let me know if you have any questions.

Best wishes,
Eralp

**Comment by xiamucp** [comment] 2023-08-06 02:15
Hi Eralp,
Thanks for your reply.
I have set the initial SSD density and turn GND density on, but the slip resistance is unchanged. The forest density in  'subroutine CP_DunneExplicit' after 'forest = forest_t + dforest' was always zero, but SSD densities decreased.
Best wishes,
Xia

**Comment by EralpDemir** [comment] 2023-08-06 08:21
Hi again Xia,
The code is structured for different models therefore many of the state variables exist even though they are not used everytime.

The forest density "forest" or "forest_t" are used in the hardening model=4, they have zero value otherwise. The actual forest projections are calculated in the rhofor local variable, and it is not outputted. You may want to setup another state variable if you want to output the forest density due to SSD and GNDs.

The tauc not changing is due to a similar reason. Because tauc is used as a state variable for hardening model=1. The tauc due to SSD and GNDs are stored in the local variable called "tauc_eff". It is also not outputted. 

I would recommend to turn off GNDs first. In the SSD evolution  there are two constants; k1 and k2. k1 is for hardening and k2 is softening. They should be carefully selected otherwise you may en up with softening right away. I would set k2=0 to check the evolution of SSDs. 

Hope this helps, let me know if you have any other issues.
Eralp

**Comment by xiamucp** [comment] 2023-08-06 09:24
Hi Eralp,

Thank you for your answer to the question. I have no other questions. 

If I find other questions later, I will consult you.

Best wishes,
Xia

**Comment by xiamucp** [comment] 2023-08-19 01:38
Dear Eralp,

I found that linear reduced integration element (C3D8R) is not concluded in element libarary. Can it be used for GND calculation?

I'm looking forward to your reply, thanks!

Bese wishes,
Xia

**Comment by EralpDemir** [comment] 2023-08-20 12:41
Hi Xia,

Yes, our GND calculation is an element based calculation meaning its done within the element.

C3D8R has only a single integration point which does not allow to calculate gradients within an element. Therefore we cannot have GNDs for that element type.

Bests,
Eralp

**Comment by xiamucp** [comment] 2023-08-21 01:44
Dear Eralp,

Thanks for your reply.

I thought over the question. Then, is it feasible to calculate the gradient by using the global positions of adjacent grain integration points?

Besets,
Xia
